# This file was generated by GoReleaser. DO NOT EDIT.
cask "manygit" do
  version "1.1.4"

  on_macos do
    on_intel do
      sha256 "a66d32fac96657336e23ff925150d91c7c2b4dc4dc0e23d1ca7a62dcbe73985a"
      url "https://github.com/rabeeh-ta/manygit/releases/download/v#{version}/manygit_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0039d225d186960678cbe6b93d0ab7e70c0722aba344dc18b7145a1b80479123"
      url "https://github.com/rabeeh-ta/manygit/releases/download/v#{version}/manygit_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "7d6a9a7a16a19ed8d5651566594bdfb669785e989634e39d0f89e017048947a6"
      url "https://github.com/rabeeh-ta/manygit/releases/download/v#{version}/manygit_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ba235447d24db8d108708a8242be356fc3616fe37b8ad642717073c439a01e46"
      url "https://github.com/rabeeh-ta/manygit/releases/download/v#{version}/manygit_linux_arm64.tar.gz"
    end
  end

  name "manygit"
  desc "Lazygit-style TUI for a whole tree of git repos"
  homepage "https://rabeeh-ta.github.io/manygit/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "manygit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/manygit"]
    end
  end

  zap trash: [
      "~/.cache/manygit",
    ]

end
