# This file was generated by GoReleaser. DO NOT EDIT.
cask "manygit" do
  version "1.1.7"

  on_macos do
    on_arm do
      sha256 "7b59ccfea4f599e292bbc07fa806045c3cdd6d4551c54718ac983fb3f8b6bd65"
      url "https://github.com/rabeeh-ta/manygit/releases/download/v#{version}/manygit_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "854175369d836cc0dc725c65aefde693697d99e090ea740e46002b2b41f92ce0"
      url "https://github.com/rabeeh-ta/manygit/releases/download/v#{version}/manygit_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "3101aa7d98645e274da1e75c3322d918375dc776f7c8ce4584e4b6865b2ba805"
      url "https://github.com/rabeeh-ta/manygit/releases/download/v#{version}/manygit_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "00f7f45e283b6e05b0925033d2d7c2925db04f721383c58e412d9eb03da4a5d1"
      url "https://github.com/rabeeh-ta/manygit/releases/download/v#{version}/manygit_linux_amd64.tar.gz"
    end
  end

  name "manygit"
  desc "Lazygit-style TUI for a whole tree of git repos"
  homepage "https://rabeeh-ta.github.io/manygit/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "manygit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/manygit"]
    end
  end

  zap trash: [
      "~/.cache/manygit",
    ]

end
