# This file was generated by GoReleaser. DO NOT EDIT.
cask "manygit" do
  version "1.1.6"

  on_macos do
    on_arm do
      sha256 "fbf0bf9853790a2c50db76faa3ef2549cdd73bf18adfa3e4ad4c69b649adb141"
      url "https://github.com/rabeeh-ta/manygit/releases/download/v#{version}/manygit_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "200a98ebba28151af2fcd216fbf684626a28ba5b7803d04da5eb74a4e1ee0c74"
      url "https://github.com/rabeeh-ta/manygit/releases/download/v#{version}/manygit_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8586309bbf257cce32fb495ed85724b055e652e2bd72b6d42bedd7c3205080b7"
      url "https://github.com/rabeeh-ta/manygit/releases/download/v#{version}/manygit_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e3ee949fe7054980d4f79686aa38f42806ffeb3e8a04d0f5d495924fb0d723fc"
      url "https://github.com/rabeeh-ta/manygit/releases/download/v#{version}/manygit_linux_amd64.tar.gz"
    end
  end

  name "manygit"
  desc "Lazygit-style TUI for a whole tree of git repos"
  homepage "https://rabeeh-ta.github.io/manygit/"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "manygit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/manygit"]
    end
  end

  zap trash: [
      "~/.cache/manygit",
    ]

end
